name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # للحصول على تاريخ Git الكامل

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # يمكنك تغيير الإصدار حسب احتياجاتك
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Build Flutter app
        run: flutter build apk --release  # أو flutter build ios لبناء iOS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "e2-gen
          git config --global user.email "ebrahimjein@gmail.com"

      - name: Push to repository
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-commit by GitHub Actions" || echo "No changes to commit"
          git push origin HEAD:main || echo "Nothing to push"
